#!/usr/bin/env python3
"""Generate golden-set expected values by running the real pipeline once.

Run this deliberately, on purpose, when a standardisation/descriptor change is
INTENDED and reviewed — never automatically. Regenerating silently would
defeat the entire point of a regression suite: the golden set exists to catch
an unintended change, and regenerating on every run would make it catch
nothing.

Usage:
    python scripts/generate_golden_fixtures.py
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from drugsim_chem import (  # noqa: E402
    DESCRIPTOR_SPEC_VERSION,
    STANDARDIZATION_PIPELINE_VERSION,
    process_structure,
)
from drugsim_core.version import get_rdkit_version  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
COMPOUNDS_CSV = ROOT / "datasets" / "golden" / "compounds.csv"
OUTPUT_JSON = ROOT / "datasets" / "golden" / "expected_output.json"


def _round_floats(obj: object, ndigits: int = 6) -> object:
    """Recursively round floats for stable, diff-friendly JSON output.

    Args:
        obj: A JSON-serialisable structure.
        ndigits: Rounding precision.

    Returns:
        The structure with all floats rounded.
    """
    if isinstance(obj, float):
        return round(obj, ndigits)
    if isinstance(obj, dict):
        return {k: _round_floats(v, ndigits) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_round_floats(v, ndigits) for v in obj]
    return obj


def main() -> int:
    """Compute and write the golden fixture."""
    with COMPOUNDS_CSV.open(newline="", encoding="utf-8") as handle:
        compounds = list(csv.DictReader(handle))

    results: dict[str, object] = {
        "_meta": {
            "rdkit_version": get_rdkit_version(),
            "standardization_pipeline_version": STANDARDIZATION_PIPELINE_VERSION,
            "descriptor_spec_version": DESCRIPTOR_SPEC_VERSION,
            "note": (
                "Generated by scripts/generate_golden_fixtures.py. A diff here "
                "on an unrelated change is a regression, not routine drift — "
                "investigate before regenerating."
            ),
        },
        "compounds": {},
    }

    errors = []
    for row in compounds:
        name = row["name"]
        try:
            result = process_structure(row["smiles"])
        except Exception as exc:  # noqa: BLE001 — collect all failures before reporting
            errors.append(f"{name} ({row['smiles']}): {type(exc).__name__}: {exc}")
            continue

        entry: dict[str, object] = {
            "smiles": row["smiles"],
            "category": row["category"],
            "is_mixture": result.is_mixture,
            "stereo_completeness": result.stereo_completeness,
            "standardization_flags": list(result.standardization.flags),
            "component_count": result.standardization.component_count,
            "standardized_smiles": result.standardized_smiles,
            "parent_smiles": result.parent_smiles,
            "identity": {
                "canonical_smiles": result.identity.canonical_smiles,
                "isomeric_smiles": result.identity.isomeric_smiles,
                "inchi": result.identity.inchi,
                "inchikey_full": result.identity.inchikey_full,
                "inchikey_skeleton": result.identity.inchikey_skeleton,
                "bemis_murcko_scaffold": result.identity.bemis_murcko_scaffold,
                "num_stereocentres": result.identity.num_stereocentres,
                "num_defined_stereocentres": result.identity.num_defined_stereocentres,
                "molecular_formula": result.identity.molecular_formula,
                "inchi_warnings": list(result.identity.inchi_warnings),
            },
        }

        if result.descriptors is not None:
            d = result.descriptors
            entry["descriptors"] = {
                "mw_g_mol": d.mw_g_mol,
                "mw_parent_g_mol": d.mw_parent_g_mol,
                "exact_mass_g_mol": d.exact_mass_g_mol,
                "logp_crippen": d.logp_crippen,
                "molar_refractivity": d.molar_refractivity,
                "tpsa_a2": d.tpsa_a2,
                "rotatable_bonds": d.rotatable_bonds,
                "aromatic_rings": d.aromatic_rings,
                "ring_count": d.ring_count,
                "heavy_atom_count": d.heavy_atom_count,
                "formal_charge": d.formal_charge,
                "hbd_lipinski": d.hbd_lipinski,
                "hba_lipinski": d.hba_lipinski,
                "hbd_strict": d.hbd_strict,
                "hba_strict": d.hba_strict,
                "heteroatom_count": d.heteroatom_count,
                "fraction_csp3": d.fraction_csp3,
                "num_stereocentres": d.num_stereocentres,
                "largest_ring_size": d.largest_ring_size,
            }
        else:
            entry["descriptors"] = None

        if result.drug_likeness is not None:
            dl = result.drug_likeness
            entry["drug_likeness"] = {
                "lipinski_violations": dl.lipinski_violations,
                "lipinski_pass": dl.lipinski_pass,
                "veber_pass": dl.veber_pass,
                "ghose_pass": dl.ghose_pass,
                "egan_pass": dl.egan_pass,
                "muegge_pass": dl.muegge_pass,
                "rule_of_three_pass": dl.rule_of_three_pass,
                "bioavailability_score": dl.bioavailability_score,
                "qed_score": dl.qed_score,
                "sa_score": dl.sa_score,
                "np_likeness_score": dl.np_likeness_score,
                "pains_alerts": dl.pains_alerts,
                "brenk_alerts": dl.brenk_alerts,
                "gsk_4_400_flag": dl.gsk_4_400_flag,
            }
        else:
            entry["drug_likeness"] = None

        results["compounds"][name] = entry

    if errors:
        print(f"{len(errors)} compound(s) failed to process:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    rounded = _round_floats(results)
    OUTPUT_JSON.write_text(json.dumps(rounded, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {len(compounds)} compounds to {OUTPUT_JSON.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
