#!/usr/bin/env python3
"""Generate the curation golden fixture by running the real pipeline once.

Same discipline as ``scripts/generate_golden_fixtures.py`` (the chemistry-
only golden set): run this deliberately when an intended, reviewed change
to curation logic changes the fixture — never automatically. This is a
separate script and a separate fixture file
(``datasets/golden/measurements.csv`` / ``expected_curation_output.json``)
from the chemistry one, deliberately: this fixture is self-contained with
its own SMILES rather than referencing ``datasets/golden/compounds.csv`` by
name, so regenerating it can never accidentally require touching that
already-passing, separately-versioned fixture (which also records its own
RDKit-version-gated golden data — mixing the two would make a curation-
rule change look like it also needed a chemistry-pipeline regeneration,
which it never does).

Uses the same ``drugsim_curation.pipeline.curate_raw_rows`` orchestration
the two live driver scripts use — this fixture proves the real pipeline
code, not a parallel reimplementation of it.
``tests/golden/test_curation_golden_regression.py`` calls the same
function fresh and compares against this file's frozen output.

Usage:
    python scripts/generate_curation_golden_fixtures.py
"""

from __future__ import annotations

import csv
import dataclasses
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from drugsim_curation import curate_raw_rows  # noqa: E402
from drugsim_curation.provenance import LicenseResolution  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
MEASUREMENTS_CSV = ROOT / "datasets" / "golden" / "measurements.csv"
OUTPUT_JSON = ROOT / "datasets" / "golden" / "expected_curation_output.json"

#: Exported for tests/golden/test_curation_golden_regression.py so the same
#: fixed inputs are used to re-run the pipeline for comparison.
FIXED_LICENSE = LicenseResolution(
    source_id="chembl_golden_fixture",
    spdx="CC-BY-SA-3.0",
    tier="red",
    commercial_ok=True,
    attribution="Synthetic golden fixture -- not real ChEMBL data",
    license_status="resolved",
)
BAD_VALIDITY_FLAGS = frozenset({"Potential transcription error", "Potential author error"})
BLOCKER_THRESHOLD_NM = 10_000.0
DATASET_VERSION = "golden-v1"
RETRIEVED_AT = "2026-01-01"
CURATED_AT = "2026-01-01T00:00:00+00:00"


def run_golden_curation():
    """Run the real curation pipeline over the golden measurements fixture.

    Returns:
        A :class:`drugsim_curation.pipeline.CurationRunResult` -- the exact
        same type the live driver scripts produce. Both this script's
        ``main()`` and the golden regression test call this function, so
        they can never silently diverge on what "run the pipeline" means.
    """
    with MEASUREMENTS_CSV.open(newline="", encoding="utf-8") as handle:
        raw_rows = list(csv.DictReader(handle))
    return curate_raw_rows(
        raw_rows,
        source_dataset_id="golden_measurements",
        endpoint="golden_fixture",
        license_resolution=FIXED_LICENSE,
        bad_validity_flags=BAD_VALIDITY_FLAGS,
        assay_metadata_by_id={},
        blocker_threshold_nm=BLOCKER_THRESHOLD_NM,
        dataset_version=DATASET_VERSION,
        retrieved_at=RETRIEVED_AT,
        curated_at=CURATED_AT,
    )


def _round_floats(obj: object, ndigits: int = 6) -> object:
    """Recursively round floats for stable, diff-friendly JSON output."""
    if isinstance(obj, float):
        return round(obj, ndigits)
    if isinstance(obj, dict):
        return {k: _round_floats(v, ndigits) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_round_floats(v, ndigits) for v in obj]
    return obj


def main() -> int:
    """Run the curation pipeline over the golden measurements and write the fixture."""
    result = run_golden_curation()

    fixture = {
        "_meta": {
            "note": (
                "Generated by scripts/generate_curation_golden_fixtures.py. "
                "A diff here on an unrelated change is a regression, not routine drift -- "
                "investigate before regenerating."
            ),
        },
        "ledger_rows": {row.measurement_id: dataclasses.asdict(row) for row in result.ledger_rows},
        "curated_compounds": {
            c.compound_id: {
                "compound_id": c.compound_id,
                "n_source_measurements_total": c.n_source_measurements_total,
                "n_source_measurements_used": c.n_source_measurements_used,
                "aggregated_ic50_nm": c.aggregated_ic50_nm,
                "aggregation_method": c.aggregation_method,
                "value_spread_log10": c.value_spread_log10,
                "is_discordant": c.is_discordant,
                "conflict_status": c.conflict_status,
                "label": c.label,
                "training_eligible": c.training_eligible,
                "exclusion_reason": c.exclusion_reason,
                "data_quality_score": c.quality.total,
                "measurement_ids": c.measurement_ids,
            }
            for c in result.curated_compounds
        },
    }

    rounded = _round_floats(fixture)
    OUTPUT_JSON.write_text(json.dumps(rounded, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(
        f"wrote {len(result.ledger_rows)} ledger rows and {len(result.curated_compounds)} "
        f"curated compounds to {OUTPUT_JSON.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
