"""Bulk-load processed compounds into ``compound`` / ``compound_descriptor`` /
``compound_drug_likeness``.

Split the same way as ``registry_sync``/``snapshots``: ``build_*`` functions
are pure (a :class:`~drugsim_chem.pipeline.ProcessedCompound` plus caller-
supplied provenance in, a row dict out — testable with no database) and
``insert_*`` functions are thin, batched inserts.

Scope note: this module assumes each ``ProcessedCompound`` it is given
already succeeded through :func:`drugsim_chem.process_structure` — parse/
standardisation failures are quarantined by the caller *before* reaching
here (that is what makes ``StructureError`` the quarantine signal per the
project's "invalid molecules must be rejected or quarantined" rule). This
module's only job is turning an already-valid processed compound into rows.

``mol`` and ``morgan_fp_r2_2048`` are generated by the RDKit Postgres
cartridge from ``standardized_smiles`` inside the INSERT itself
(``mol_from_smiles``/``morganbv_fp``), not serialised from Python RDKit
objects — the same approach already used by
``tests/constraints/factories.py``. This keeps a second, Python-side RDKit
serialisation path from ever being able to drift from what the cartridge
itself would produce from the same SMILES.

Known limitation (flagged, not fixed, in Phase 2 — see the Phase 2 completion
report): ``identity.inchikey_full`` is computed on the *standardised*
(salt-stripped, charge-neutral) structure (Sprint 2.5/2.6), which is the same
structure ``parent_inchikey`` is meant to represent (Phase 1 Step 2 §5: "Exact
... Deduplication of identical entities" vs "Parent ... Links salt forms to
parent"). In the current pipeline the two coincide whenever a parent is
identified, so two different salt forms of the same active ingredient would
collide on ``uq_compound_inchikey`` instead of being stored as distinct
entities linked by a shared ``parent_inchikey``. This module reproduces that
existing pipeline behaviour rather than inventing a divergent one during a
bulk-load change; resolving it requires computing an entity-level identity
before salt stripping, which is a chemistry-pipeline change, not a loader
change, and is recommended for early Phase 3 before ingesting sources
(ChEMBL/BindingDB) where salt-form duplication is common.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional

from sqlalchemy import text
from sqlalchemy.orm import Session

from drugsim_chem.pipeline import ProcessedCompound
from drugsim_core.ids import generate_ulid

__all__ = [
    "BuiltRows",
    "BulkLoadResult",
    "CompoundProvenance",
    "build_compound_row",
    "build_descriptor_row",
    "build_drug_likeness_row",
    "build_rows",
    "ensure_descriptor_spec",
    "ensure_toolchain",
    "insert_compound_descriptors",
    "insert_compound_drug_likeness",
    "insert_compounds",
    "load_compounds",
]


@dataclass(frozen=True)
class CompoundProvenance:
    """Provenance fields shared by every row in one bulk-load batch.

    One value per load run: a single ETL run ingests from one source and one
    snapshot, under one toolchain and one descriptor spec, at one
    pipeline/application version — so these are supplied once here rather
    than threaded individually through every row-building call.

    Attributes:
        source_id: ``data_source.source_id`` this batch was ingested from.
        snapshot_id: ``ingestion_snapshot.snapshot_id`` the raw bytes were
            landed under (Sprint 2.4) — the provenance link back to the
            immutable Z1 file this batch was parsed from.
        source_license: The licence text as it stood at acquisition (kept
            per-row, not looked up from the registry's current value, so a
            later relicensing does not retroactively change the terms this
            record was ingested under).
        license_tier: One of ``license_tier_t`` (``green``/``amber``/``red``/
            ``black``).
        is_commercial_ok: Whether this source's licence permits commercial
            use.
        toolchain_id: The ``toolchain`` row these compounds were computed
            under (RDKit + Python + standardisation pipeline versions).
        descriptor_spec_version: The ``descriptor_spec`` row these
            descriptors were computed under.
        pipeline_version: Git SHA of the ETL code performing this load.
        drugsim_release: Application semver at load time.
        created_by: ``system_user.user_uid`` attributed with creating these
            rows — use :data:`drugsim_core.ids.SYSTEM_USER_UID` for an
            unattended batch load.
    """

    source_id: str
    snapshot_id: str
    source_license: str
    license_tier: str
    is_commercial_ok: bool
    toolchain_id: str
    descriptor_spec_version: str
    pipeline_version: str
    drugsim_release: str
    created_by: str


@dataclass(frozen=True)
class BuiltRows:
    """The rows built for one processed compound.

    Attributes:
        compound: Always present.
        descriptor: ``None`` for a flagged mixture — there is nothing to
            insert, matching ``ProcessedCompound.descriptors`` being
            ``None`` for the same reason.
        drug_likeness: ``None`` alongside ``descriptor`` for the same
            reason.
    """

    compound: dict[str, Any]
    descriptor: Optional[dict[str, Any]]
    drug_likeness: Optional[dict[str, Any]]


@dataclass(frozen=True)
class BulkLoadResult:
    """Counts from one :func:`load_compounds` call."""

    compounds_loaded: int
    descriptors_loaded: int
    drug_likeness_loaded: int
    mixtures_without_descriptors: int


def build_compound_row(
    processed: ProcessedCompound,
    provenance: CompoundProvenance,
    *,
    source_record_id: Optional[str] = None,
    compound_uid: Optional[str] = None,
) -> dict[str, Any]:
    """Build the ``compound`` row for one processed compound.

    Args:
        processed: Output of :func:`drugsim_chem.process_structure`.
        provenance: Shared batch provenance.
        source_record_id: The upstream source's own record id for this
            compound, if the source has one (e.g. a ChEMBL molecule id).
        compound_uid: Surrogate key. Generated if omitted — callers doing
            deterministic testing should supply one explicitly.

    Returns:
        A dict of column values ready to bind into an INSERT.
    """
    identity = processed.identity
    has_parent = processed.parent_smiles is not None
    return {
        "compound_uid": compound_uid or generate_ulid(),
        "source_smiles": processed.source_smiles,
        "canonical_smiles": identity.canonical_smiles,
        "isomeric_smiles": identity.isomeric_smiles,
        "standardized_smiles": processed.standardized_smiles,
        "parent_smiles": processed.parent_smiles,
        "inchi": identity.inchi,
        "inchikey_full": identity.inchikey_full,
        "inchikey_skeleton": identity.inchikey_skeleton,
        # See module docstring's "Known limitation" note: inchikey_full and
        # parent_inchikey coincide today because identity is computed on the
        # already-salt-stripped structure.
        "parent_inchikey": identity.inchikey_full if has_parent else None,
        "molecular_formula": identity.molecular_formula,
        "bemis_murcko_scaffold": identity.bemis_murcko_scaffold,
        "stereo_completeness": processed.stereo_completeness,
        "standardization_flags": list(processed.standardization.flags),
        "component_count": processed.standardization.component_count,
        "is_mixture": processed.is_mixture,
        "source_id": provenance.source_id,
        "source_record_id": source_record_id,
        "snapshot_id": provenance.snapshot_id,
        "source_license": provenance.source_license,
        "license_tier": provenance.license_tier,
        "is_commercial_ok": provenance.is_commercial_ok,
        "toolchain_id": provenance.toolchain_id,
        "pipeline_version": provenance.pipeline_version,
        "drugsim_release": provenance.drugsim_release,
        "created_by": provenance.created_by,
    }


def build_descriptor_row(
    compound_uid: str,
    processed: ProcessedCompound,
    provenance: CompoundProvenance,
) -> Optional[dict[str, Any]]:
    """Build the ``compound_descriptor`` row, or ``None`` for a mixture.

    Args:
        compound_uid: The compound this descriptor set belongs to — must
            match the ``compound_uid`` used in the corresponding
            :func:`build_compound_row` call.
        processed: Output of :func:`drugsim_chem.process_structure`.
        provenance: Shared batch provenance.

    Returns:
        A row dict, or ``None`` when ``processed.descriptors is None``
        (flagged mixture — there is no well-defined single structure to
        describe).
    """
    d = processed.descriptors
    if d is None:
        return None
    return {
        "compound_uid": compound_uid,
        "descriptor_spec_version": provenance.descriptor_spec_version,
        "mw_g_mol": d.mw_g_mol,
        "mw_parent_g_mol": d.mw_parent_g_mol,
        "exact_mass_g_mol": d.exact_mass_g_mol,
        "logp_crippen": d.logp_crippen,
        "molar_refractivity": d.molar_refractivity,
        "tpsa_a2": d.tpsa_a2,
        "rotatable_bonds": d.rotatable_bonds,
        "aromatic_rings": d.aromatic_rings,
        "ring_count": d.ring_count,
        "heavy_atom_count": d.heavy_atom_count,
        "formal_charge": d.formal_charge,
        "hbd_lipinski": d.hbd_lipinski,
        "hba_lipinski": d.hba_lipinski,
        "hbd_strict": d.hbd_strict,
        "hba_strict": d.hba_strict,
        "heteroatom_count": d.heteroatom_count,
        "fraction_csp3": d.fraction_csp3,
        "num_stereocentres": d.num_stereocentres,
        "largest_ring_size": d.largest_ring_size,
    }


def build_drug_likeness_row(
    compound_uid: str,
    processed: ProcessedCompound,
    provenance: CompoundProvenance,
) -> Optional[dict[str, Any]]:
    """Build the ``compound_drug_likeness`` row, or ``None`` for a mixture.

    Args:
        compound_uid: The compound this verdict set belongs to.
        processed: Output of :func:`drugsim_chem.process_structure`.
        provenance: Shared batch provenance.

    Returns:
        A row dict, or ``None`` when ``processed.drug_likeness is None``.
    """
    dl = processed.drug_likeness
    if dl is None:
        return None
    return {
        "compound_uid": compound_uid,
        "descriptor_spec_version": provenance.descriptor_spec_version,
        "lipinski_violations": dl.lipinski_violations,
        "lipinski_pass": dl.lipinski_pass,
        "veber_pass": dl.veber_pass,
        "ghose_pass": dl.ghose_pass,
        "egan_pass": dl.egan_pass,
        "muegge_pass": dl.muegge_pass,
        "rule_of_three_pass": dl.rule_of_three_pass,
        "bioavailability_score": dl.bioavailability_score,
        "qed_score": dl.qed_score,
        "sa_score": dl.sa_score,
        "np_likeness_score": dl.np_likeness_score,
        "pains_alerts": dl.pains_alerts,
        "brenk_alerts": dl.brenk_alerts,
        "pfizer_3_75_flag": dl.pfizer_3_75_flag,
        "gsk_4_400_flag": dl.gsk_4_400_flag,
    }


def build_rows(
    processed: ProcessedCompound,
    provenance: CompoundProvenance,
    *,
    source_record_id: Optional[str] = None,
    compound_uid: Optional[str] = None,
) -> BuiltRows:
    """Build all three rows for one processed compound in one call.

    Args:
        processed: Output of :func:`drugsim_chem.process_structure`.
        provenance: Shared batch provenance.
        source_record_id: The upstream source's own record id, if any.
        compound_uid: Surrogate key. Generated if omitted.

    Returns:
        The built rows, with ``descriptor``/``drug_likeness`` as ``None``
        for a flagged mixture.
    """
    compound_row = build_compound_row(
        processed, provenance, source_record_id=source_record_id, compound_uid=compound_uid
    )
    uid = compound_row["compound_uid"]
    return BuiltRows(
        compound=compound_row,
        descriptor=build_descriptor_row(uid, processed, provenance),
        drug_likeness=build_drug_likeness_row(uid, processed, provenance),
    )


_INSERT_COMPOUND_SQL = text(
    "INSERT INTO compound (compound_uid, source_smiles, canonical_smiles, "
    "isomeric_smiles, standardized_smiles, parent_smiles, inchi, "
    "inchikey_full, inchikey_skeleton, parent_inchikey, molecular_formula, "
    "bemis_murcko_scaffold, stereo_completeness, standardization_flags, "
    "component_count, is_mixture, mol, morgan_fp_r2_2048, source_id, "
    "source_record_id, snapshot_id, source_license, license_tier, "
    "is_commercial_ok, toolchain_id, pipeline_version, drugsim_release, "
    "created_by) "
    "VALUES (:compound_uid, :source_smiles, :canonical_smiles, "
    ":isomeric_smiles, :standardized_smiles, :parent_smiles, :inchi, "
    ":inchikey_full, :inchikey_skeleton, :parent_inchikey, "
    ":molecular_formula, :bemis_murcko_scaffold, :stereo_completeness, "
    ":standardization_flags, :component_count, :is_mixture, "
    "mol_from_smiles(:standardized_smiles), "
    "morganbv_fp(mol_from_smiles(:standardized_smiles), 2), :source_id, "
    ":source_record_id, :snapshot_id, :source_license, :license_tier, "
    ":is_commercial_ok, :toolchain_id, :pipeline_version, :drugsim_release, "
    ":created_by)"
)

_INSERT_DESCRIPTOR_SQL = text(
    "INSERT INTO compound_descriptor (compound_uid, descriptor_spec_version, "
    "mw_g_mol, mw_parent_g_mol, exact_mass_g_mol, logp_crippen, "
    "molar_refractivity, tpsa_a2, rotatable_bonds, aromatic_rings, "
    "ring_count, heavy_atom_count, formal_charge, hbd_lipinski, "
    "hba_lipinski, hbd_strict, hba_strict, heteroatom_count, fraction_csp3, "
    "num_stereocentres, largest_ring_size) "
    "VALUES (:compound_uid, :descriptor_spec_version, :mw_g_mol, "
    ":mw_parent_g_mol, :exact_mass_g_mol, :logp_crippen, "
    ":molar_refractivity, :tpsa_a2, :rotatable_bonds, :aromatic_rings, "
    ":ring_count, :heavy_atom_count, :formal_charge, :hbd_lipinski, "
    ":hba_lipinski, :hbd_strict, :hba_strict, :heteroatom_count, "
    ":fraction_csp3, :num_stereocentres, :largest_ring_size)"
)

_INSERT_DRUG_LIKENESS_SQL = text(
    "INSERT INTO compound_drug_likeness (compound_uid, "
    "descriptor_spec_version, lipinski_violations, lipinski_pass, "
    "veber_pass, ghose_pass, egan_pass, muegge_pass, rule_of_three_pass, "
    "bioavailability_score, qed_score, sa_score, np_likeness_score, "
    "pains_alerts, brenk_alerts, pfizer_3_75_flag, gsk_4_400_flag) "
    "VALUES (:compound_uid, :descriptor_spec_version, :lipinski_violations, "
    ":lipinski_pass, :veber_pass, :ghose_pass, :egan_pass, :muegge_pass, "
    ":rule_of_three_pass, :bioavailability_score, :qed_score, :sa_score, "
    ":np_likeness_score, :pains_alerts, :brenk_alerts, :pfizer_3_75_flag, "
    ":gsk_4_400_flag)"
)


def insert_compounds(session: Session, rows: list[dict[str, Any]]) -> int:
    """Batch-insert ``compound`` rows.

    Args:
        session: An active session, expected to be used inside
            :func:`drugsim_db.audit.audit_context` so the audit trigger has
            attribution to record.
        rows: From :func:`build_compound_row` (or :func:`build_rows`).

    Returns:
        The number of rows inserted (``len(rows)``; SQLAlchemy's executemany
        does not report per-row counts reliably across dialects, so this
        reflects intent rather than a driver-reported count).
    """
    if not rows:
        return 0
    session.execute(_INSERT_COMPOUND_SQL, rows)
    return len(rows)


def insert_compound_descriptors(session: Session, rows: list[dict[str, Any]]) -> int:
    """Batch-insert ``compound_descriptor`` rows. See :func:`insert_compounds`."""
    if not rows:
        return 0
    session.execute(_INSERT_DESCRIPTOR_SQL, rows)
    return len(rows)


def insert_compound_drug_likeness(session: Session, rows: list[dict[str, Any]]) -> int:
    """Batch-insert ``compound_drug_likeness`` rows. See :func:`insert_compounds`."""
    if not rows:
        return 0
    session.execute(_INSERT_DRUG_LIKENESS_SQL, rows)
    return len(rows)


def load_compounds(
    session: Session,
    processed_compounds: list[ProcessedCompound],
    provenance: CompoundProvenance,
    *,
    source_record_ids: Optional[list[Optional[str]]] = None,
) -> BulkLoadResult:
    """Build and insert one batch of already-processed compounds.

    Callers must have already registered ``provenance.toolchain_id`` and
    ``provenance.descriptor_spec_version`` (see :func:`ensure_toolchain` /
    :func:`ensure_descriptor_spec`) and must run this inside
    :func:`drugsim_db.audit.audit_context` for the governed-table audit
    trigger to have attribution to record.

    Args:
        session: An active session.
        processed_compounds: Already-successful pipeline outputs — parse/
            standardisation failures must be quarantined by the caller
            before reaching this function (see module docstring).
        provenance: Shared batch provenance.
        source_record_ids: Per-compound upstream record ids, same length and
            order as ``processed_compounds``. Omit if the source has none.

    Returns:
        Counts of what was inserted.

    Raises:
        ValueError: If ``source_record_ids`` is given with the wrong length
            — a silent off-by-one here would misattribute provenance.
    """
    if source_record_ids is not None and len(source_record_ids) != len(processed_compounds):
        msg = (
            f"source_record_ids length ({len(source_record_ids)}) must match "
            f"processed_compounds length ({len(processed_compounds)})"
        )
        raise ValueError(msg)

    record_ids: list[Optional[str]] = source_record_ids or [None] * len(processed_compounds)

    built = [
        build_rows(processed, provenance, source_record_id=record_id)
        for processed, record_id in zip(processed_compounds, record_ids)
    ]

    compound_rows = [b.compound for b in built]
    descriptor_rows = [b.descriptor for b in built if b.descriptor is not None]
    drug_likeness_rows = [b.drug_likeness for b in built if b.drug_likeness is not None]

    insert_compounds(session, compound_rows)
    insert_compound_descriptors(session, descriptor_rows)
    insert_compound_drug_likeness(session, drug_likeness_rows)

    return BulkLoadResult(
        compounds_loaded=len(compound_rows),
        descriptors_loaded=len(descriptor_rows),
        drug_likeness_loaded=len(drug_likeness_rows),
        mixtures_without_descriptors=sum(1 for p in processed_compounds if p.is_mixture),
    )


def ensure_toolchain(
    session: Session,
    *,
    toolchain_id: str,
    rdkit_version: str,
    python_version: str,
    std_pipeline_ver: str,
) -> None:
    """Register a ``toolchain`` row if it does not already exist.

    Toolchain rows are append-only by convention (P8: nothing deleted or
    silently altered) — ``ON CONFLICT DO NOTHING`` makes re-running this for
    an already-known toolchain a no-op rather than an error, which matters
    for an ETL step that may be re-run.

    Args:
        session: An active session.
        toolchain_id: See :func:`drugsim_core.version.build_toolchain_id`.
        rdkit_version: RDKit version this toolchain pins.
        python_version: Python version this toolchain pins.
        std_pipeline_ver: ``drugsim_chem`` standardisation pipeline version.
    """
    session.execute(
        text(
            "INSERT INTO toolchain (toolchain_id, rdkit_version, "
            "python_version, std_pipeline_ver) "
            "VALUES (:tid, :rdkit, :python, :stdpipe) "
            "ON CONFLICT (toolchain_id) DO NOTHING"
        ),
        {
            "tid": toolchain_id,
            "rdkit": rdkit_version,
            "python": python_version,
            "stdpipe": std_pipeline_ver,
        },
    )


def ensure_descriptor_spec(
    session: Session,
    *,
    descriptor_spec_version: str,
    toolchain_id: str,
    feature_set_id: str,
    descriptor_list: list[str],
    hbd_convention: str = "lipinski",
    hba_convention: str = "lipinski",
    rotb_strict: bool = False,
) -> None:
    """Register a ``descriptor_spec`` row if it does not already exist.

    Args:
        session: An active session.
        descriptor_spec_version: The version string (matches
            ``drugsim_chem.DESCRIPTOR_SPEC_VERSION``).
        toolchain_id: The toolchain this spec was computed under — must
            already exist (see :func:`ensure_toolchain`).
        feature_set_id: See :func:`drugsim_features.compute_feature_set_id`.
        descriptor_list: Descriptor column names this spec covers.
        hbd_convention: Which HBD definition rule evaluation uses. Defaults
            to ``"lipinski"`` — matches ``drugsim_chem.drug_likeness``, which
            always evaluates rules against the ``*_lipinski`` fields, never
            ``*_strict`` (Phase 1 Step 4 §E.1 correction).
        hba_convention: As above, for HBA.
        rotb_strict: Whether rotatable-bond counting uses RDKit's strict
            definition. Defaults to ``False`` — ``compute_descriptors`` uses
            ``Lipinski.NumRotatableBonds``, the non-strict count.
    """
    session.execute(
        text(
            "INSERT INTO descriptor_spec (descriptor_spec_version, "
            "toolchain_id, hbd_convention, hba_convention, rotb_strict, "
            "descriptor_list, feature_set_id) "
            "VALUES (:version, :tid, :hbd, :hba, :rotb, :dlist, :fsid) "
            "ON CONFLICT (descriptor_spec_version) DO NOTHING"
        ),
        {
            "version": descriptor_spec_version,
            "tid": toolchain_id,
            "hbd": hbd_convention,
            "hba": hba_convention,
            "rotb": rotb_strict,
            "dlist": descriptor_list,
            "fsid": feature_set_id,
        },
    )
